<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:

In [3]:
# importing numpy
import numpy as np

In [25]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array1 = np.array([1,2,3,5,0])
print(f"The array: {array1}")
print(f"Are all the elements non-zero? {array1.all()}")

The array: [1 2 3 5 0]
Are all the elements non-zero? False


In [26]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array2 = np.array([3,-1,3,7,2])
print(f"The array: {array2}")
print(f"Is any element non-zero? {array2.any()}")

The array: [ 3 -1  3  7  2]
Is any element non-zero? True


In [29]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array3 = np.array([0]*4)
print(f"The array: {array3}")
print(f"Is any element non-zero? {array3.any()}")

The array: [0 0 0 0]
Is any element non-zero? False


In [32]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array4 = np.array([56,-2,7])
print(array4)
print(array4.size)

[56 -2  7]
3


In [39]:
# Create a numpy array with 10 zeros and print the array.
array_zeros = np.zeros(10)
print(array_zeros)
# Create a numpy array with 6 ones and print the array.
array_ones = np.ones(6)
print(array_ones)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
array_threes = np.array([3]*12)
print(array_threes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [49]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array_range = np.arange(8,21)
print(array_range)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
array_even = np.arange(8,21,2)
print(array_even)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [72]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array100 = np.random.normal(2,0.5,100)
print("100 Elements array:")
print(f"Mean of the array: {random_array100.mean()}")
print(f"Maximum number in the array: {random_array100.max()}")
print(f"Minimum number in the array: {random_array100.min()}")
print(f"Standard deviation of the array: {random_array100.std()}")
print("\n")
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array1000 = np.random.normal(2,0.5,1000)
print("1,000 Elements array:")
print(f"Mean of the array: {random_array1000.mean()}")
print(f"Maximum number in the array: {random_array1000.max()}")
print(f"Minimum number in the array: {random_array1000.min()}")
print(f"Standard deviation of the array: {random_array1000.std()}")
print("\n")
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array1000000 = np.random.normal(2,0.5,100000)
print("100,000 Elements array:")
print(f"Mean of the array: {random_array100000.mean()}")
print(f"Maximum number in the array: {random_array100000.max()}")
print(f"Minimum number in the array: {random_array100000.min()}")
print(f"Standard deviation of the array: {random_array100000.std()}")
print("\n")
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
print("While the number of elements increases in the array, the mean of the array gets closer to 2.")

100 Elements array:
Mean of the array: 1.9870038075490615
Maximum number in the array: 3.5109101542069445
Minimum number in the array: 0.9441196589969636
Standard deviation of the array: 0.4762053323582924


1,000 Elements array:
Mean of the array: 1.9747269743348366
Maximum number in the array: 3.8404001346270515
Minimum number in the array: 0.4146063536924256
Standard deviation of the array: 0.4976686288183949


100,000 Elements array:
Mean of the array: 2.004677506106646
Maximum number in the array: 4.12116874489445
Minimum number in the array: 0.18067108974895585
Standard deviation of the array: 0.5088346194748767


While the number of elements increases in the array, the mean of the array gets closer to 2.
