<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [7]:
A = np.array([[5, 2, 3], [6, 1, 3], [2, 4, 1]])

In [8]:
A

array([[5, 2, 3],
       [6, 1, 3],
       [2, 4, 1]])

In [9]:
b=A[0:2,0:2]

In [10]:
b

array([[5, 2],
       [6, 1]])

In [11]:
c=A[1:,1:]

In [12]:
c

array([[1, 3],
       [4, 1]])