In [20]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

In [12]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [5]:
# Create a linear SVM classifier
clf = svm.SVC(kernel='linear')

In [13]:
X = iris.data
y = iris.target

In [14]:
print("First 10 rows of the iris dataset:")
print(X[:10, :])

print("First 10 target labels:")
print(y[:10])

First 10 rows of the iris dataset:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
First 10 target labels:
[0 0 0 0 0 0 0 0 0 0]


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [22]:
# Create a linear SVM classifier
linear_svm = SVC(kernel='linear')

# Train the linear SVM classifier on the training data
linear_svm.fit(X_train, y_train)

# Make predictions on the test data
y_pred_linear = linear_svm.predict(X_test)

# Calculate the accuracy of the linear SVM
accuracy_linear = accuracy_score(y_test, y_pred_linear)

print("Accuracy of the Linear SVM:", accuracy_linear)

Accuracy of the Linear SVM: 1.0


In [23]:
# Define the hyperparameter grid to search
param_grid = {'C': [0.1, 1, 10, 100],
              'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
              'gamma': ['scale', 'auto']}

# Create a GridSearchCV object
grid_search = GridSearchCV(SVC(), param_grid, cv=5)

# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

# Get the best parameters from the grid search
best_params = grid_search.best_params_

# Create an SVM classifier with the best hyperparameters
best_svm = SVC(**best_params)

# Train the SVM classifier on the training data
best_svm.fit(X_train, y_train)

# Make predictions on the test data using the best SVM
y_pred_best = best_svm.predict(X_test)

# Calculate the accuracy of the best SVM
accuracy_best = accuracy_score(y_test, y_pred_best)

print("Best Hyperparameters:", best_params)
print("Accuracy of the Best SVM:", accuracy_best)


Best Hyperparameters: {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}
Accuracy of the Best SVM: 0.9777777777777777


In [24]:
print("Accuracy of the Linear SVM:", accuracy_linear)
print("Accuracy of the Best SVM:", accuracy_best)


Accuracy of the Linear SVM: 1.0
Accuracy of the Best SVM: 0.9777777777777777
