<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:


In [1]:
print("Albin Babu Varghese\nAli Guneysel\nErinda Kapllani\nJai Vigneshwar Aiyyappan\nKaushal Ghelani\nKumud\nMadhoumithaa Veerasethu\nRajvi Patel\n")

Albin Babu Varghese
Ali Guneysel
Erinda Kapllani
Jai Vigneshwar Aiyyappan
Kaushal Ghelani
Kumud
Madhoumithaa Veerasethu
Rajvi Patel



In [2]:
# importing numpy
import numpy as np

In [3]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
array1 = np.array([1,2,3,5,0])
print(f"The array: {array1}")
print(f"Are all the elements non-zero? {array1.all()}")

The array: [1 2 3 5 0]
Are all the elements non-zero? False


In [4]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
array2 = np.array([3,-1,3,7,2])
print(f"The array: {array2}")
print(f"Is any element non-zero? {array2.any()}")

The array: [ 3 -1  3  7  2]
Is any element non-zero? True


In [5]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
array3 = np.array([0]*4)
print(f"The array: {array3}")
print(f"Is any element non-zero? {array3.any()}")

The array: [0 0 0 0]
Is any element non-zero? False


In [6]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
array4 = np.array([56,-2,7])
print(array4)
print(array4.size*array4.itemsize)

[56 -2  7]
24


In [7]:
# Create a numpy array with 10 zeros and print the array.
array_zeros = np.zeros(10)
print(array_zeros)
# Create a numpy array with 6 ones and print the array.
array_ones = np.ones(6)
print(array_ones)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
array_threes = np.array([3]*12)
print(array_threes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [8]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array_range = np.arange(8,21)
print(array_range)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
array_even = np.arange(8,21,2)
print(array_even)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [9]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array100 = np.random.normal(2,0.5,100)
print("100 Elements array:")
print(f"Mean of the array: {random_array100.mean()}")
print(f"Maximum number in the array: {random_array100.max()}")
print(f"Minimum number in the array: {random_array100.min()}")
print(f"Standard deviation of the array: {random_array100.std()}")
print("\n")
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array1000 = np.random.normal(2,0.5,1000)
print("1,000 Elements array:")
print(f"Mean of the array: {random_array1000.mean()}")
print(f"Maximum number in the array: {random_array1000.max()}")
print(f"Minimum number in the array: {random_array1000.min()}")
print(f"Standard deviation of the array: {random_array1000.std()}")
print("\n")
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array1000000 = np.random.normal(2,0.5,1000000)
print("1,000,000 Elements array:")
print(f"Mean of the array: {random_array1000000.mean()}")
print(f"Maximum number in the array: {random_array1000000.max()}")
print(f"Minimum number in the array: {random_array1000000.min()}")
print(f"Standard deviation of the array: {random_array1000000.std()}")
print("\n")
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
print("Even if the numbers of elements in the array change, the mean and standard deviation almost tend to stay same.")

100 Elements array:
Mean of the array: 2.0112077678999105
Maximum number in the array: 3.2547936060455402
Minimum number in the array: 0.7953990302708618
Standard deviation of the array: 0.5165796792257943


1,000 Elements array:
Mean of the array: 2.0221978546157793
Maximum number in the array: 3.560386026422762
Minimum number in the array: 0.5049657084240073
Standard deviation of the array: 0.5164004373980395


1,000,000 Elements array:
Mean of the array: 2.000315991846026
Maximum number in the array: 4.326020678684581
Minimum number in the array: -0.27458327795414483
Standard deviation of the array: 0.4994862830018054


Even if the numbers of elements in the array change, the mean and standard deviation almost tend to stay same.
